"""
Git Utilities
"""

import subprocess
import sys
from pathlib import Path


def is_git_repo() -> bool:
    try:
        subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            capture_output=True, check=True
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def get_staged_diff(files: list = None) -> str:
    """Get the diff of staged changes."""
    try:
        cmd = ["git", "diff", "--cached"]
        if files:
            cmd += ["--"] + files
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        return result.stdout
    except Exception:
        return ""


def get_staged_files(files: list = None) -> list:
    """Get list of staged files."""
    try:
        if files:
            return files
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True, text=True, timeout=30
        )
        return [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]
    except Exception:
        return []


def do_commit(message: str) -> bool:
    """Execute the git commit."""
    try:
        result = subprocess.run(
            ["git", "commit", "-m", message],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(result.stdout)
            return True
        else:
            print(f"Commit failed: {result.stderr}")
            return False
    except Exception as e:
        print(f"Error: {e}")
        return False


def install_hook():
    """Install as git prepare-commit-msg hook."""
    git_dir = Path(subprocess.check_output(
        ["git", "rev-parse", "--git-dir"],
        text=True
    ).strip())

    hook_path = git_dir / "hooks" / "prepare-commit-msg"
    hook_content = f"""#!/bin/sh
# Auto-generated by git-commit-gen
if [ "$2" = "" ]; then
    python3 {Path(sys.argv[0]).absolute()} --provider rule-based --auto-commit 2>/dev/null || true
fi
"""
    hook_path.write_text(hook_content)
    hook_path.chmod(0o755)
    print(f"✅ Hook installed at: {hook_path}")
    print("Now 'git commit' will auto-suggest messages!")
